# Generated by Django 5.2 on 2025-04-30 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensors', '0002_sensor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='distancia',
            field=models.CharField(default='0', max_length=150, verbose_name='DISTANCIA'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='humedad',
            field=models.CharField(default='0', max_length=150, verbose_name='HUMEDAD'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='potenciometro',
            field=models.CharField(default='0', max_length=150, verbose_name='POTENCIOMETRO'),
        ),
        migrations.AddField(
            model_name='sensor',
            name='temperatura',
            field=models.CharField(default='0', max_length=150, verbose_name='TEMPERATURA'),
        ),
    ]
